# Naive Bayes

Naive Bayes methods are a set of supervised learning algorithms based on applying Bayes' theorem with the "naive" assumption of conditional independence between every pair of features given the value of the class variable. Bayes'theorem states the following relationship, given class variable $y$ and dependent feature vector $x_1$ through $x_n$,:

$$P(y \mid x_1, \dots, x_n) = \frac{P(y) P(x_1, \dots x_n \mid y)}
                                 {P(x_1, \dots, x_n)}$$

Using the naive conditional independence assumption, we have

$$\begin{align}\begin{aligned}P(y \mid x_1, \dots, x_n) \propto P(y) \prod_{i=1}^{n} P(x_i \mid y)\\\Downarrow\\\hat{y} = \arg\max_y P(y) \prod_{i=1}^{n} P(x_i \mid y),\end{aligned}\end{align}$$

Then, we can use Maximum A Posteriori (MAP) estimation to estimate $P(y)$ and $P(x_i \mid y)$; the former is then the relative frequency of class $y$ in the training set.

*References*:
H. Zhang (2004). The optimality of Naive Bayes. Proc. FLAIRS.

# 1 Gaussian Naive Bayes

GaussianNB implements the Gaussian Naive Bayes algorithm for classification.   
The likelihood of the features is assumed to be Gaussian:

$$P(x_i \mid y) = \frac{1}{\sqrt{2\pi\sigma^2_y}} \exp\left(-\frac{(x_i - \mu_y)^2}{2\sigma^2_y}\right)$$

The parameters $\sigma_y$ and $\mu_y$  are estimated using maximum likelihood.

**Example** - The training data is generated as follows:

In [17]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])

**Q1**: Training a GaussianNB model:

In [18]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X,y)

GaussianNB(priors=None, var_smoothing=1e-09)

**Q2**: Predict the label of a data [-0.8,-1]:

In [29]:
X_test = np.array([[-0.8,-1]])
y_pred = gnb.predict(X_test)
y_pred

array([1])

# 2 MultinomialNB

The multinomial Naive Bayes classifier is suitable for classification with discrete features (e.g., word counts for text classification). 

*References*   
C.D. Manning, P. Raghavan and H. Schuetze (2008). Introduction to Information Retrieval. Cambridge University Press, pp. 234-265. http://nlp.stanford.edu/IR-book/html/htmledition/naive-bayes-text-classification-1.html

**Example** - The training data is generated as follows:

In [20]:
import numpy as np
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])
X.shape

(6, 100)

**Q3**: Training a MultinomialNB model:

In [21]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X,y)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

**Q4**: Predict the label of a data X[2:3]:

In [24]:
X[2:3]

array([[0, 4, 4, 1, 3, 3, 1, 4, 0, 0, 2, 3, 3, 1, 4, 2, 1, 3, 3, 2, 0, 0,
        3, 1, 4, 2, 1, 1, 2, 0, 3, 0, 3, 1, 0, 2, 2, 3, 4, 1, 0, 1, 2, 1,
        0, 2, 1, 0, 0, 4, 2, 0, 2, 4, 3, 0, 2, 0, 2, 4, 2, 3, 1, 1, 0, 1,
        0, 2, 3, 1, 1, 1, 3, 0, 0, 3, 4, 1, 0, 2, 4, 2, 0, 2, 0, 3, 4, 1,
        0, 4, 3, 3, 1, 4, 0, 4, 3, 3, 3, 1]])

In [25]:
clf.predict(X[2:3])

array([3])

# 3 Process on 'Iris' Data

In Week 9, we have studied how to use KNN algorithm to do classification task on 'iris' data. Here,we are going to employ the GaussianNB to conduct the same task. 

In [65]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris_dataset = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'], random_state=0)

In [66]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(112, 4)
(112,)
(38, 4)
(38,)


**Q5**：Report the acuracy result on test data:

In [41]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf1.fit(X_test,y_test)
clf2.fit(X_test,y_test)
from sklearn.metrics import accuracy_score
print("Acc: on test set by using GaussianNB: ", accuracy_score(y_test, clf1.predict(X_test)))
print("Acc: on test set by using MultinomialNB: ", accuracy_score(y_test, clf2.predict(X_test)))

Acc: on test set by using GaussianNB:  1.0
Acc: on test set by using MultinomialNB:  0.7631578947368421


# 4 Predict Human Activity Recognition (HAR)

The objective of this practice exercise is to predict current human activity based on phisiological activity measurements from 53 different features based in the [HAR dataset](http://groupware.les.inf.puc-rio.br/har#sbia_paper_section). The training (`har_train.csv`) and test (`har_validate.csv`) datasets are provided.

**Q6**: Build a Naive Bayes model, predict on the test dataset and compute the [confusion matrix](https://towardsdatascience.com/understanding-confusion-matrix-a9ad42dcfd62). Note: Please refer to the [`sklearn.metrics.confusion_matrix`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html)

In [67]:
import pandas as pd
train = pd.read_csv("har_train.csv")
test = pd.read_csv("har_validate.csv")
print("shape of train set: ", train.shape)
print("shape of test set: ", test.shape)

shape of train set:  (13737, 53)
shape of test set:  (5885, 53)


In [68]:
train.head()

classe  roll_belt  pitch_belt  yaw_belt  total_accel_belt  gyros_belt_x  \
0      A       1.41        8.07     -94.4                 3          0.00   
1      A       1.41        8.07     -94.4                 3          0.02   
2      A       1.42        8.07     -94.4                 3          0.00   
3      A       1.48        8.05     -94.4                 3          0.02   
4      A       1.45        8.06     -94.4                 3          0.02   

   gyros_belt_y  gyros_belt_z  accel_belt_x  accel_belt_y  ...  \
0           0.0         -0.02           -21             4  ...   
1           0.0         -0.02           -22             4  ...   
2           0.0         -0.02           -20             5  ...   
3           0.0         -0.03           -22             3  ...   
4           0.0         -0.02           -21             4  ...   

   total_accel_forearm  gyros_forearm_x  gyros_forearm_y  gyros_forearm_z  \
0                   36             0.03             0.00            -0.02   
1                   36             0.02             0.00            -0.02   
2                   36             0.03            -0.02             0.00   
3                   36             0.02            -0.02             0.00   
4                   36             0.02            -0.02            -0.03   

   accel_forearm_x  accel_forearm_y  accel_forearm_z  magnet_forearm_x  \
0              192              203             -215               -17   
1              192              203             -216               -18   
2              196              204             -213               -18   
3              189              206             -214               -16   
4              193              203             -215                -9   

   magnet_forearm_y  magnet_forearm_z  
0               654               476  
1               661               473  
2               658               469  
3               658               469  
4               660               478  

[5 rows x 53 columns]

In [69]:
set(train['classe'])

{'A', 'B', 'C', 'D', 'E'}

In [70]:
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [71]:
names = ["Nearest Neighbors", "Linear SVM", "RBF SVM", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "QDA"]

In [72]:
classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1, max_iter=1000),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis()]

In [73]:
for name, clf in zip(names, classifiers):
        print("Classe: ", name)
        clf.fit(X_train, y_train)
        score = clf.score(X_test, y_test)
        print("acc: ", score)

Classe:  Nearest Neighbors
acc:  0.9736842105263158
Classe:  Linear SVM
acc:  0.9210526315789473
Classe:  RBF SVM
acc:  0.9736842105263158
Classe:  Gaussian Process
acc:  0.9736842105263158
Classe:  Decision Tree
acc:  0.9736842105263158
Classe:  Random Forest
acc:  0.9473684210526315
Classe:  Neural Net
acc:  0.9736842105263158
Classe:  AdaBoost
acc:  0.8947368421052632
Classe:  Naive Bayes
acc:  1.0
Classe:  QDA
acc:  0.9736842105263158


In [74]:
knn = KNeighborsClassifier(3)
knn.fit(X_train, y_train)
score = knn.score(X_test,y_test)
print("acc: ", score)

acc:  0.9736842105263158


In [75]:
dt = DecisionTreeClassifier(max_depth=5)
dt.fit(X_train, y_train)
score = knn.score(X_test,y_test)
print("acc: ", score)

acc:  0.9736842105263158


In [76]:
ml = MLPClassifier(alpha=1, max_iter=1000)
ml.fit(X_train, y_train)
score = knn.score(X_test,y_test)
print("acc: ", score)

acc:  0.9736842105263158


In [77]:
ad = AdaBoostClassifier()
ad.fit(X_train, y_train)
score = knn.score(X_test,y_test)
print("acc: ", score)

acc:  0.9736842105263158
